import localFont from "next/font/local";
import "./globals.css";
import { Suspense } from "react";
import { Loading } from "@/Loading";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Suspense fallback={<Loading />}>
          <Navbar />
          <main className="flex-grow">{children}</main>{" "}
          {/* Main content grows */}
          <Footer /> {/* Footer stays at the bottom */}
        </Suspense>
      </body>
    </html>
  );
}
